AllCops:
  TargetRubyVersion:
    2.5.8
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  NewCops: enable

Naming/VariableNumber:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact

Style/ClassVars:
  Enabled: false

Layout/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 60

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Max: 1500

Metrics/ModuleLength:
  Max: 300

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/HashSyntax:
  EnforcedStyle: ruby19

Lint/SuppressedException:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: true

Style/PreferredHashMethods:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Lint/Debugger:
  Enabled: false

# there are some rare valid scenarios where this is OK
Style/GlobalVars:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/ExtraSpacing:
  ForceEqualSignAlignment: false

Metrics/ParameterLists:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false  